version: "3.3"

services:
  mariadb:
    image: mariadb:10.5.8
    container_name: cismariadb
    hostname: cismariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  redis:
    image: redis:6.2.5-alpine
    restart: always
    container_name: cisredis
    hostname: cisredis
    ports:
      - "6379:6379"
    command: redis-server /redis.conf --requirepass ${REDIS_PASSWORD} 
    volumes:
      - ./data/redis:/data
      - ./config/redis.conf:/redis.conf
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    container_name: cisrabbitmq
    hostname: cisrabbitmq
    env_file:
      - ./.env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - cisgraderoom
networks:
  cisgraderoom:
    external: true


    # docker network create -d bridge cisgraderoom
